"""Initial migration

Revision ID: 56df425b62c4
Revises: 
Create Date: 2025-08-04 16:35:17.953783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '56df425b62c4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('encounter',
    sa.Column('encounter_date', sa.Date(), nullable=False),
    sa.Column('encounter_time', sa.Time(), nullable=False),
    sa.Column('invitation', sa.Text(), nullable=True),
    sa.Column('venue', sa.String(length=100), nullable=True),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('person',
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('attending', sa.Boolean(), nullable=False),
    sa.Column('encounter_id', sa.Uuid(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounter.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('pet',
    sa.Column('pet_name', sa.String(length=100), nullable=True),
    sa.Column('pet_type', sa.Enum('DOG', 'CAT', 'OTHER', name='pettype'), nullable=False),
    sa.Column('link', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('encounter_id', sa.Uuid(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounter.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pet')
    op.drop_table('person')
    op.drop_table('encounter')
    # ### end Alembic commands ###
